### ISSUE TITLE
Are you open for contribution? 

### ISSUE THREAD

**Issue by PrajjwalDatir** [Devansu-Yadav/9x9-TicTacToe#2]
I am willing to make it better.
I have experience in Python pygame
if possible please opt in your repo into HacktoberFest2020 with giving it hacktoberfest tag

**Comment by Devansu-Yadav** [comment]
Hi, @PrajjwalDatir see I have no problem with that. It's just that I am looking to make a web version of this game using Django framework, so I won't be using pygame then. Although u can contribute and make a Pr if you feel you can make the Game better.
